// <auto-generated />
namespace CryptoTracker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class cryptodto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cryptodto));
        
        string IMigrationMetadata.Id
        {
            get { return "202406161210063_crypto-dto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
